### PR TITLE
fix: fix image size in croping popup

### PR DESCRIPTION
**Pull request by KonstantinBel**
https://jira.railsc.ru/browse/BPC-19097

### CODE REVIEW

**Comment by KonstantinBel** [comment]
@Nats92 -> idbolshakov

**Comment by KonstantinBel** [comment]
:warning: branch - bz2021-july-2

**Review by Nats92 — APPROVED** [review]

**Comment by Nats92** [comment]
@idbolshakov

**Review by idbolshakov — APPROVED** [review]

**Comment by KonstantinBel** [comment]
@TamarinEA

**Pull request merged**
